### ISSUE TITLE
`enabled` field in facet results does not respect `search_string`

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/datahost-prototypes#65]
I've just noticed a bug in the implementation of facet results introduced in #63, in that it returns incorrect results in the presence of a `search_string`.  

I suspect this is because it is calculating the facets `enabled` status before filtering by the search string.

Example queries to show the issue:

[This query](http://35.234.148.167/ide?query=%7B%0A%20%20endpoint%20%7B%0A%20%20%20%20catalog%20%7B%0A%20%20%20%20%20%20catalog_query(search_string%3A%22hmrc%22%0A%20%20%20%20%20%20%20%20%20themes%3A%5B%22http%3A%2F%2Fgss-data.org.uk%2Fdef%2Fgdp%23trade%22%5D%0A%20%20%20%20%20%20)%20%7B%0A%20%20%20%20%20%20%20%20datasets%20%7B%0A%20%20%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%20%20%20%20creator%0A%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20facets%20%7B%0A%20%20%20%20%20%20%20%20%20%20creators%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20enabled%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20themes%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20enabled%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) locks the `trade` theme and searches within it for a string of "hmrc":
```graphql
{
  endpoint {
    catalog {
      catalog_query(search_string:"hmrc"
         themes:["http://gss-data.org.uk/def/gdp#trade"]
      ) {
        datasets {
          title
          creator

        }
        facets {
          creators {
            enabled
            id
          }
          themes {
            enabled
            id
          }
        }
      }
    }
  }
}
```

The elided results below first show all datasets in the results have a creator of `hmrc` as expected: 

```json
          "datasets": [
            {
              "creator": "https://www.gov.uk/government/organisations/hm-revenue-customs"
            },
            {
              "creator": "https://www.gov.uk/government/organisations/hm-revenue-customs"
            },
            {
              "creator": "https://www.gov.uk/government/organisations/hm-revenue-customs"
            },
            {
              "creator": "https://www.gov.uk/government/organisations/hm-revenue-customs"
            },
            {
              "creator": "https://www.gov.uk/government/organisations/hm-revenue-customs"
            }
          ],
```

However in the facets branch for creator we see: 

```
...
              {
                "enabled": true,
                "id": "https://www.gov.uk/government/organisations/hm-revenue-customs"
              },
...
              {
                "enabled": true,
                "id": "https://www.gov.uk/government/organisations/department-for-digital-culture-media-sport"
              },
...
```

Which is wrong, because the only enabled facet should be `https://www.gov.uk/government/organisations/hm-revenue-customs`.

Removing the search string returns the expected distinct two creators : 

```
            {
              "creator": "https://www.gov.uk/government/organisations/department-for-digital-culture-media-sport"
            },
            {
              "creator": "https://www.gov.uk/government/organisations/hm-revenue-customs"
            },
...
```

So it looks like we're just not applying the search string to the facets.

**Comment by rosado** [comment]
How is the search string supposed to affect the facets?

1. Only show facets matching the search string?
2. Only enable facets matching the search string?

**Comment by kiramclean** [comment]
The search string does not apply directly to the facets; only indirectly via the dataset results. The `enabled` flag on the facets reflects the available subsets of datasets. The high-level idea is that a facet will have `enabled` set to `true` _if selecting that facet would return any **datasets**._ The purpose of this is to allow construction of UIs that assist users in making relevant selections. A facet should not be enabled if selecting it would be a dead-end selection leading to no results.

So in this case, with the search string `hmrc` applied and the "themes" facet locked to `trade` there are 5 datasets that have _both_ the trade theme and `hmrc` in their titles or descriptions, and they all have the same creator (`...hm-revenue-customs`). The facets branch for `creators` should only show as enabled creators that would result in more (or the same number of) datasets being returned if selected, so in this case the only enabled creator should be the one that all the returned datasets share, i.e. `...hm-revenue-customs`. If you were to lock the creators facet to `...department-for-digital-culture-media-sport` in this case you would end up with no results (since there are 0 datasets that match `hmrc` in their titles or descriptions _and_ have the trade theme _and_ have the "department-for-digital-culture-media-sport" creator, so it should not be enabled.
